SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS model_has_permissions;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;  