 CREATE TABLE IF NOT EXISTS campaign_registrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  campaign_id INT NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
   otp_code VARCHAR(10) NULL,
  otp_used TINYINT(1) DEFAULT 0,
  otp_attempts INT DEFAULT 0,
  otp_expires_at DATETIME NULL,
  verified_at DATETIME NULL,
  picked_up TINYINT(1) DEFAULT 0,
  picked_up_at DATETIME NULL,
  pickup_center VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
  
);
