CREATE TABLE IF NOT EXISTS corridor_feedbacks (
  id INT PRIMARY KEY AUTO_INCREMENT,
  corridor_id VARCHAR(50) NOT NULL,
  user_id INT NOT NULL,
  comment TEXT,
  rating INT CHECK (rating BETWEEN 1 AND 5),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (corridor_id) REFERENCES corridors(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
