CREATE TABLE IF NOT EXISTS faqs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  faq_title VARCHAR(500) NOT NULL,
  slug VARCHAR(500) NOT NULL UNIQUE,
  faq_description TEXT NOT NULL,
  faq_type VARCHAR(50) NOT NULL DEFAULT 'shop',
  issued_by VARCHAR(100) NOT NULL DEFAULT 'Admin',
  language VARCHAR(10) NOT NULL DEFAULT 'en',
  translated_languages JSON NOT NULL,
  shop_id INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_shop_id (shop_id),
  CONSTRAINT fk_faq_shop FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
