CREATE TABLE IF NOT EXISTS order_status (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    serial INT NOT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    color VARCHAR(7) DEFAULT '#000000',
    translated_languages TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
