 
CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  owner_id INT NOT NULL, 
  description TEXT,
  type_id INT,
  price DECIMAL(10,2),
  shop_id INT,
  sale_price DECIMAL(10,2) DEFAULT NULL,
  language VARCHAR(10),
  min_price DECIMAL(10,2),
  max_price DECIMAL(10,2),
  sku VARCHAR(255),
  preview_url VARCHAR(255),
  quantity INT,
  in_stock BOOLEAN DEFAULT 1,
  is_taxable BOOLEAN DEFAULT 0,
  shipping_class_id INT DEFAULT NULL,
  status VARCHAR(50),
  product_type VARCHAR(50),
  unit VARCHAR(50),
  height DECIMAL(10,2) DEFAULT NULL,
  width DECIMAL(10,2) DEFAULT NULL,
  length DECIMAL(10,2) DEFAULT NULL,
  image JSON DEFAULT NULL,
  video JSON DEFAULT NULL,
  gallery JSON DEFAULT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  author_id INT DEFAULT NULL,
  manufacturer_id INT DEFAULT NULL,
  is_digital BOOLEAN DEFAULT 0,
  is_external BOOLEAN DEFAULT 0,
  external_product_url VARCHAR(255) DEFAULT NULL,
  external_product_button_text VARCHAR(255) DEFAULT NULL,
  orders_count INT DEFAULT 0,
  ratings DECIMAL(3,2) DEFAULT NULL,
  total_reviews INT DEFAULT 0,
  rating_count JSON DEFAULT NULL,
  my_review JSON DEFAULT NULL,
  in_wishlist BOOLEAN DEFAULT 0,
  total_downloads INT DEFAULT 0,
  blocked_dates JSON DEFAULT NULL,
  translated_languages JSON DEFAULT NULL,
  shop JSON DEFAULT NULL,
  tags JSON DEFAULT NULL,
  type JSON DEFAULT NULL,
  categories JSON DEFAULT NULL,
  digital_file JSON DEFAULT NULL,
  countries_id INT NOT NULL,
  FOREIGN KEY (countries_id) REFERENCES countries(id)
);

