CREATE TABLE IF NOT EXISTS taxes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  country VARCHAR(255) NOT NULL,
  state VARCHAR(255) DEFAULT NULL,
  zip VARCHAR(20) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  rate DECIMAL(5,2) NOT NULL,
  name VARCHAR(255) NOT NULL,
  is_global BOOLEAN DEFAULT NULL,
  priority INT DEFAULT NULL,
  on_shipping BOOLEAN NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);
