DROP TABLE IF EXISTS types;
CREATE TABLE IF NOT EXISTS types (
 id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  settings JSON DEFAULT NULL,
  slug VARCHAR(255) NOT NULL,
  language VARCHAR(10) NOT NULL,
  icon VARCHAR(100) DEFAULT NULL,
  promotional_sliders_id INT DEFAULT NULL,
  promotional_sliders_original VARCHAR(500) DEFAULT NULL,
  promotional_sliders_thumbnail VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);